/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownCodeBtn: typeof import('./src/components/home/barElement/components/downCodeBtn.vue')['default']
    H5header: typeof import('./src/components/releasePage/preview/H5header.vue')['default']
    HomeBar: typeof import('./src/components/home/homeBar.vue')['default']
    HomeBreadCrumb: typeof import('./src/components/home/homeBreadCrumb.vue')['default']
    HomeNav: typeof import('./src/components/home/homeNav.vue')['default']
    LoginFormLogin: typeof import('./src/components/login/loginFormLogin.vue')['default']
    LoginFormRegister: typeof import('./src/components/login/loginFormRegister.vue')['default']
    MicroAside: typeof import('./src/components/microMain/microAside.vue')['default']
    MicroContainer: typeof import('./src/components/microMain/microContainer.vue')['default']
    MicroEditor: typeof import('./src/components/microMain/microEditor.vue')['default']
    MicroMainBtn: typeof import('./src/components/home/barElement/microMainBtn.vue')['default']
    PageContent: typeof import('./src/components/releasePage/preview/pageContent.vue')['default']
    PreviewPage: typeof import('./src/components/releasePage/previewPage.vue')['default']
    ReleaseFun: typeof import('./src/components/releasePage/releaseFun.vue')['default']
    ReleaseFunction: typeof import('./src/components/releasePage/releaseFunction.vue')['default']
    ReleaseNav: typeof import('./src/components/releasePage/releaseNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    WXheader: typeof import('./src/components/releasePage/preview/WXheader.vue')['default']
  }
}
