/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeBar: typeof import('./src/components/home/homeBar.vue')['default']
    HomeBreadCrumb: typeof import('./src/components/home/homeBreadCrumb.vue')['default']
    HomeNav: typeof import('./src/components/home/homeNav.vue')['default']
    LoginFormLogin: typeof import('./src/components/login/loginFormLogin.vue')['default']
    LoginFormRegister: typeof import('./src/components/login/loginFormRegister.vue')['default']
    MicroAside: typeof import('./src/components/microMain/microAside.vue')['default']
    MicroContainer: typeof import('./src/components/microMain/microContainer.vue')['default']
    MicroEditor: typeof import('./src/components/microMain/microEditor.vue')['default']
    MicroMainBtn: typeof import('./src/components/home/barElement/microMainBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
  }
}
