version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    environment:
      - API_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - '8000:8000'
